### ISSUE TITLE
Error generating Trapezoid gradient

### ISSUE THREAD

**Issue by ritagnunes** [imr-framework/pypulseq#8]
When trying to generate a trapezoid gradient by providing only its axis, amplitude and duration I get the following error:

UnboundLocalError: local variable 'amplitude_temp' referenced before assignment

**Comment by sravan953** [comment]
Fixed in e5055aafd9fa766bd43fed3e80ff82514ff2f0aa.

**Comment by ritagnunes** [comment]
I am still getting the same error...

When running
"g=make_trapezoid(channel='x',system=system, amplitude=system.max_grad,duration=0.010)"

I get the error message:

  File "make_trap_pulse.py", line 87, in make_trapezoid
    abs(amplitude2) / max_slew / system.grad_raster_time) * system.grad_raster_time
UnboundLocalError: local variable 'amplitude2' referenced before assignment

**Comment by sravan953** [comment]
Can you please share the system parameters?

**Comment by ritagnunes** [comment]
system = Opts(max_grad=32, grad_unit='mT/m', max_slew=130, slew_unit='T/m/s', rf_ringdown_time=30e-6,rf_dead_time=100e-6)
